//
//  BDLocData.h
//  BarrickMotion
//
//  Created by Kevin Hunt on 2017-06-09.
//  Copyright © 2017 Prophet Studios. All rights reserved.
//

#import <Foundation/Foundation.h>
#import "BDConstants.h"

/**
 * Represents a collection of sensor data at a certain location at a certain timestamp, generated by a certain driver on a certain route
 */
@interface BDLocData : NSObject

@property (nonatomic, nullable, strong, readonly) NSString *timestamp;
@property (nonatomic, nullable, strong, readonly) NSString *driverID;
@property (nonatomic, nullable, strong, readonly) NSString *routeID;
@property (nonatomic, nullable, strong, readonly) NSString *tripID;
@property (nonatomic, readonly) BDMotionManagerViolationType violation;
@property (nonatomic, readonly) float longitude;
@property (nonatomic, readonly) float latitude;
@property (nonatomic, readonly) float accX;
@property (nonatomic, readonly) float accY;
@property (nonatomic, readonly) float accZ;
@property (nonatomic, readonly) float gyroX;
@property (nonatomic, readonly) float gyroY;
@property (nonatomic, readonly) float gyroZ;

/**
 * Returns a BDLocData instance for the dictionary of values
 * @param dict An dictionary of values and keys representing the properties of the BDLocData class
 * @return A BDLocData instance
 */
- (instancetype _Nullable )initWithDictionary:(NSDictionary *_Nonnull)dict;

/**
 * The value of the sensor data for the given type
 * @param sensorType The enum value representing the sensor for desired value
 * @return The value for the requested sensor
 */
- (float)valueForSensorType:(BDMotionManagerSensorType)sensorType;
@end
