//
//  BDTripData.h
//  BarrickMotion
//
//  Created by Kevin Hunt on 2017-04-18.
//  Copyright © 2017 Prophet Studios. All rights reserved.
//

#import <Foundation/Foundation.h>
#import "BDConstants.h"
#import "BDRouteData.h"

/**
 * Represents the metadata and BDLocData values of a given trip, generated by a certain driver on a certain route
 */
@interface BDTripData : NSObject

// Metadata
@property (nonatomic, nullable, strong) NSString *timestamp;
@property (nonatomic, nullable, strong) NSString *driverID;
@property (nonatomic, nullable, strong) NSString *routeID;
@property (nonatomic, nullable, strong) NSString *tripID;
@property (nonatomic, nullable, strong) NSString *score;
@property (nonatomic, nullable, strong) NSString *load;
@property (nonatomic, nullable, strong) NSString *date;
@property (nonatomic, nullable, strong) NSString *time;
@property (nonatomic, nullable, strong) BDRouteData *routeObj;

// Sensor data
@property (nonatomic, nullable, strong) NSArray *locationDataPoints; // An array of BDLocData objects

/**
 * Returns a BDTripData instance for the dictionary of values
 * @param dict An dictionary of values and keys representing the metadata properties of the BDTripData class
 * @return A BDTripData instance
 */
- (instancetype _Nullable )initWithDictionary:(NSDictionary *_Nonnull)dict;

@end
